name: couldai_user_app
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  fl_chart: ^0.66.0
  intl: ^0.19.0

flutter:
  uses-material-design: true

  fonts:
    - family: Vazir
      fonts:
        - asset: fonts/Vazir-Regular.ttf
        - asset: fonts/Vazir-Bold.ttf
          weight: 700

  assets:
    - images/